SELECT C.ID,	C.GENOTYPE,	P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C
# 부모 대장균 선택
JOIN ECOLI_DATA P ON P.ID = C.PARENT_ID	
# 부모의 형질을 모두 가지는 자식 대장균 선택
WHERE P.GENOTYPE & C.GENOTYPE = P.GENOTYPE 
ORDER BY ID;