SELECT ID,	EMAIL,	FIRST_NAME,	LAST_NAME
FROM DEVELOPERS 
# Python, C# 코드가 각 개발자의 스킬코드에 포함되는지 확인
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID;