SELECT YEAR,	(MAX_COLONY - SIZE_OF_COLONY) AS YEAR_DEV,	ID
FROM ECOLI_DATA e1
# 연도별 가장 큰 대장균의 크기를 나타내는 테이블과 join
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
      FROM ECOLI_DATA 
      GROUP BY YEAR(DIFFERENTIATION_DATE)) e2 
      ON YEAR(DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR, YEAR_DEV;